"""OSM onboarding wizard: frameworks, golden draft, refinement, must-have fields."""

from __future__ import annotations

import re
from copy import deepcopy
from datetime import date
from pathlib import Path
from typing import Any, Callable

import yaml

from tools.osm_common.semantics import (
    ITSM_OFFERING_TOKENS,
    PRODUCT_SERVICE_TOKENS,
    VENDOR_STACK_TOKENS,
    normalised_name,
    tokenize,
)
from tools.osm_scaffold.frameworks import Framework, discover_frameworks
from tools.osm_scaffold.golden import DOMAINS, propose_draft
from tools.osm_scaffold.state import (
    clear_state,
    empty_state,
    load_state,
    render_tree,
    save_state,
)

SEGMENT = r"^[a-z0-9]+(?:-[a-z0-9]+)*$"
PROVIDER_TYPES = (
    "cloud-infrastructure",
    "cloud-platform",
    "managed-service",
    "software-vendor",
    "network-provider",
    "data-center",
)
SUBSTITUTABILITY = ("low", "medium", "high")
LIFECYCLE = ("draft", "pilot", "production", "sunset", "retired")
DORA_PILLARS = (
    "ICT Risk Management",
    "ICT-related Incident Management",
    "Digital Operational Resilience Testing",
    "ICT Third-Party Risk Management",
)
DORA_CRITICALITY = ("critical", "important", "standard")
AI_RISK = ("unacceptable", "high-risk", "limited-risk", "minimal-risk", "not-applicable")
NIST_FUNCTIONS = ("govern", "identify", "protect", "detect", "respond", "recover")
TOGAF_DOMAINS = ("Business", "Data", "Application", "Technology")


class ScaffoldError(ValueError):
    """User input cannot become a valid OSM catalog fragment."""


class SaveAndExit(Exception):
    """User typed :save. Checkpoint written; wizard stops."""


def slugify(value: str) -> str:
    return normalised_name(value)


def _is_segment(value: str) -> bool:
    return bool(re.match(SEGMENT, value or ""))


def refuse_stack_id(stack_id: str) -> None:
    token = normalised_name(stack_id)
    if token in VENDOR_STACK_TOKENS or any(part in VENDOR_STACK_TOKENS for part in tokenize(stack_id)):
        raise ScaffoldError(
            f"stack id {stack_id!r} is a vendor tower. Use an adopter competency "
            "(compute, identity, data), not aws/azure/m365."
        )
    if not _is_segment(stack_id):
        raise ScaffoldError(f"stack id {stack_id!r} must be a lowercase hyphenated slug")


def refuse_vendor_label(label: str) -> None:
    token = normalised_name(label)
    if token in VENDOR_STACK_TOKENS or any(part in VENDOR_STACK_TOKENS for part in tokenize(label)):
        raise ScaffoldError(
            f"{label!r} is a vendor name. OSM domains and stacks are capabilities "
            "(Cloud Infrastructure, Identity), not AWS / Microsoft."
        )


def refuse_service_slug(slug: str, name: str | None = None) -> None:
    if not _is_segment(slug):
        raise ScaffoldError(f"service slug {slug!r} must be a lowercase hyphenated slug")
    tokens = set(tokenize(slug))
    if name:
        tokens.update(tokenize(name))
    hits = sorted(token for token in tokens if token in PRODUCT_SERVICE_TOKENS)
    if hits:
        token = hits[0]
        capability, product = PRODUCT_SERVICE_TOKENS[token]
        raise ScaffoldError(
            f"service slug/name uses product token {token!r} ({product}). "
            f"Name the capability (e.g. {capability}) and put {product} on an Offering."
        )


def refuse_offering_slug(slug: str, name: str | None = None) -> None:
    if not _is_segment(slug):
        raise ScaffoldError(f"offering slug {slug!r} must be a lowercase hyphenated slug")
    haystack = f"-{normalised_name(slug)}-"
    hits = [token for token in ITSM_OFFERING_TOKENS if f"-{token}-" in haystack]
    if hits:
        raise ScaffoldError(
            f"offering slug looks like an ITSM request ({', '.join(hits)}). "
            "Offerings are technological variants, not ticket types."
        )


def _prompt(ask: Callable[[str], str], message: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default not in (None, "") else ""
    raw = ask(f"{message}{suffix}: ").strip()
    if raw:
        return raw
    if default is not None:
        return default
    return ""


def _load_yaml_file(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    with path.open(encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise ScaffoldError(f"{path} is not a mapping document")
    return data


def _dump_yaml(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        handle.write(
            "# Generated by osm-scaffold. OSM 1.3.0 catalog fragment.\n"
            "# Posture is omitted/empty on purpose: unknown is better than invented.\n\n"
        )
        yaml.safe_dump(
            payload,
            handle,
            sort_keys=False,
            default_flow_style=False,
            allow_unicode=True,
        )


def build_records(config: dict[str, Any]) -> dict[str, Any]:
    stack = config.get("stack") or {}
    service = config.get("service") or {}
    offerings = config.get("offerings") or []
    providers = config.get("providers") or []

    stack_id = slugify(str(stack.get("id") or ""))
    stack_name = str(stack.get("name") or stack_id).strip()
    refuse_stack_id(stack_id)
    if not stack_name:
        raise ScaffoldError("stack name is required")

    service_slug = slugify(str(service.get("slug") or service.get("id") or ""))
    service_name = str(service.get("name") or "").strip()
    refuse_service_slug(service_slug, service_name or service_slug)
    if not service_name:
        raise ScaffoldError("service name is required")
    if not offerings:
        raise ScaffoldError("a Service must have at least one Offering")

    service_id = f"{stack_id}.{service_slug}"
    accountable = str(service.get("accountable") or "Service Owner").strip()
    description = str(service.get("description") or service_name).strip()
    lifecycle = str(service.get("lifecycle_state") or "draft").strip()
    if lifecycle not in LIFECYCLE:
        raise ScaffoldError(f"lifecycle_state {lifecycle!r} is not an OSM value")
    version = str(service.get("version") or "1.0.0")
    valid_from = str(service.get("valid_from") or date.today().isoformat())

    offering_rows: list[dict[str, Any]] = []
    provider_ids_used: list[str] = []
    for item in offerings:
        slug = slugify(str(item.get("slug") or item.get("id") or ""))
        name = str(item.get("name") or slug).strip()
        refuse_offering_slug(slug, name)
        offering_id = f"{service_id}.{slug}"
        row: dict[str, Any] = {
            "id": offering_id,
            "name": name,
        }
        if item.get("description"):
            row["description"] = str(item["description"]).strip()
        provider_id = item.get("provider_id") or item.get("provider")
        if provider_id:
            pid = slugify(str(provider_id))
            row["providers"] = [pid]
            provider_ids_used.append(pid)
        offering_rows.append(row)

    provider_rows: list[dict[str, Any]] = []
    seen_providers: set[str] = set()
    for item in providers:
        pid = slugify(str(item.get("id") or ""))
        if not pid or pid in seen_providers:
            continue
        ptype = str(item.get("type") or "cloud-infrastructure")
        if ptype not in PROVIDER_TYPES:
            raise ScaffoldError(f"provider type {ptype!r} is not an OSM ICT Provider type")
        subst = str(item.get("substitutability") or "medium")
        if subst not in SUBSTITUTABILITY:
            raise ScaffoldError(f"substitutability {subst!r} is not an OSM value")
        seen_providers.add(pid)
        provider_rows.append(
            {
                "id": pid,
                "name": str(item.get("name") or pid),
                "type": ptype,
                "substitutability": subst,
                "gdpr_dpa_signed": None,
                "dora_notification_clause": None,
                "certifications": [],
                "risk_level": None,
            }
        )
    for pid in provider_ids_used:
        if pid in seen_providers:
            continue
        seen_providers.add(pid)
        provider_rows.append(
            {
                "id": pid,
                "name": pid,
                "type": "cloud-infrastructure",
                "substitutability": "medium",
                "gdpr_dpa_signed": None,
                "dora_notification_clause": None,
                "certifications": [],
                "risk_level": None,
            }
        )

    return {
        "stack": {
            "id": stack_id,
            "name": stack_name,
            "description": str(stack.get("description") or f"{stack_name} technological services.").strip(),
        },
        "service": {
            "id": service_id,
            "name": service_name,
            "description": description,
            "accountable": accountable,
            "technology_stack": stack_name,
            "version": version,
            "valid_from": valid_from,
            "valid_to": None,
            "lifecycle_state": lifecycle,
            "service_offerings": offering_rows,
        },
        "providers": provider_rows,
    }


def merge_into_catalog(root: Path, records: dict[str, Any]) -> None:
    stacks_path = root / "catalog" / "technology-stacks.yaml"
    services_path = root / "catalog" / "services.yaml"
    providers_path = root / "catalog" / "ict-providers.yaml"
    posture_path = root / "posture" / "service-posture.yaml"

    stacks_doc = _load_yaml_file(stacks_path)
    services_doc = _load_yaml_file(services_path)
    providers_doc = _load_yaml_file(providers_path)
    posture_doc = _load_yaml_file(posture_path)

    stacks = list(stacks_doc.get("technology_stacks") or [])
    services = list(services_doc.get("services") or [])
    providers = list(providers_doc.get("ict_providers") or [])
    posture = list(posture_doc.get("service_posture") or [])

    new_stack = records["stack"]
    existing_stack = next(
        (row for row in stacks if isinstance(row, dict) and row.get("id") == new_stack["id"]),
        None,
    )
    if existing_stack is not None:
        if existing_stack.get("name"):
            records["service"]["technology_stack"] = existing_stack["name"]
    elif any(isinstance(row, dict) and row.get("name") == new_stack["name"] for row in stacks):
        raise ScaffoldError(f"a stack named {new_stack['name']!r} already exists with a different id")
    else:
        stacks.append(new_stack)

    new_service = records["service"]
    if any(isinstance(row, dict) and row.get("id") == new_service["id"] for row in services):
        raise ScaffoldError(f"service id {new_service['id']!r} already exists")
    services.append(new_service)

    existing_provider_ids = {row.get("id") for row in providers if isinstance(row, dict)}
    for provider in records["providers"]:
        if provider["id"] not in existing_provider_ids:
            providers.append(provider)
            existing_provider_ids.add(provider["id"])

    _dump_yaml(stacks_path, {"technology_stacks": stacks})
    _dump_yaml(services_path, {"services": services})
    _dump_yaml(providers_path, {"ict_providers": providers})
    _dump_yaml(posture_path, {"service_posture": posture})


def records_as_yaml(records: dict[str, Any]) -> str:
    payload = {
        "technology_stacks": [records["stack"]],
        "services": [records["service"]],
        "ict_providers": records["providers"],
        "service_posture": [],
    }
    return yaml.safe_dump(payload, sort_keys=False, default_flow_style=False, allow_unicode=True)


def load_config(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ScaffoldError(f"{path} must contain a mapping")
    return deepcopy(data)


def collect_interactive(ask: Callable[[str], str] | None = None) -> dict[str, Any]:
    """One-service path (used by --config tests and non-wizard callers)."""
    ask = ask or input
    print("osm-scaffold — declare a technological service. Unknown posture is left unset.")
    stack_id = slugify(_prompt(ask, "Technology stack id (competency, not a vendor)", "compute"))
    refuse_stack_id(stack_id)
    stack_name = _prompt(ask, "Technology stack name", stack_id.replace("-", " ").title())
    stack_description = _prompt(
        ask,
        "Stack description",
        f"{stack_name} technological services.",
    )
    service_slug = slugify(_prompt(ask, "Service slug (capability, not a product)", "kubernetes"))
    service_name = _prompt(ask, "Service name", service_slug.replace("-", " ").title())
    refuse_service_slug(service_slug, service_name)
    service_description = _prompt(ask, "Service description", service_name)
    accountable = _prompt(ask, "Service Owner (accountable)", "Service Owner")

    offerings: list[dict[str, Any]] = []
    providers: list[dict[str, Any]] = []
    print("Add at least one Offering (variant). Empty offering slug ends the list.")
    while True:
        default_slug = "aws-eks" if not offerings else ""
        offering_slug = slugify(_prompt(ask, "Offering slug", default_slug))
        if not offering_slug:
            if offerings:
                break
            print("A Service needs at least one Offering.")
            continue
        offering_name = _prompt(ask, "Offering name", offering_slug.replace("-", " "))
        refuse_offering_slug(offering_slug, offering_name)
        provider_id = slugify(_prompt(ask, "ICT Provider id (legal seller, empty if self-operated)", ""))
        item: dict[str, Any] = {"slug": offering_slug, "name": offering_name}
        if provider_id:
            item["provider_id"] = provider_id
            if not any(row.get("id") == provider_id for row in providers):
                provider_name = _prompt(ask, "Provider name", provider_id)
                provider_type = _prompt(ask, f"Provider type {PROVIDER_TYPES}", "cloud-infrastructure")
                subst = _prompt(ask, f"Substitutability {SUBSTITUTABILITY}", "medium")
                providers.append(
                    {
                        "id": provider_id,
                        "name": provider_name,
                        "type": provider_type,
                        "substitutability": subst,
                    }
                )
        offerings.append(item)
        more = _prompt(ask, "Add another offering? [y/N]", "n").lower()
        if more not in {"y", "yes"}:
            break

    return {
        "stack": {"id": stack_id, "name": stack_name, "description": stack_description},
        "service": {
            "slug": service_slug,
            "name": service_name,
            "description": service_description,
            "accountable": accountable,
            "lifecycle_state": "draft",
        },
        "offerings": offerings,
        "providers": providers,
    }


def write_catalog_from_state(catalog_dir: Path, state: dict[str, Any]) -> None:
    """Emit standard OSM layout under catalog_dir (catalog/ + posture/)."""
    stacks = deepcopy(state.get("stacks") or [])
    services_in = deepcopy(state.get("services") or [])
    providers = deepcopy(state.get("providers") or [])
    if not stacks:
        raise ScaffoldError("cannot compile: no Technology Stacks")
    if not services_in:
        raise ScaffoldError("cannot compile: no Services")

    stack_by_id = {row["id"]: row for row in stacks}
    services_out: list[dict[str, Any]] = []
    used_providers: set[str] = set()
    today = date.today().isoformat()
    for service in services_in:
        offerings = list(service.get("offerings") or [])
        if not offerings:
            raise ScaffoldError(f"service {service.get('id')!r} needs at least one Offering")
        stack_name = service.get("technology_stack")
        if not any(row.get("name") == stack_name for row in stacks):
            prefix = str(service.get("id") or "").split(".")[0]
            if prefix in stack_by_id:
                service["technology_stack"] = stack_by_id[prefix]["name"]
        row = {
            "id": service["id"],
            "name": service["name"],
            "description": service.get("description") or service["name"],
            "accountable": service.get("accountable") or "Service Owner",
            "technology_stack": service["technology_stack"],
            "version": str(service.get("version") or "1.0.0"),
            "valid_from": service.get("valid_from") or today,
            "valid_to": service.get("valid_to"),
            "lifecycle_state": service.get("lifecycle_state") or "draft",
            "service_offerings": [],
        }
        if service.get("characteristics"):
            row["characteristics"] = service["characteristics"]
        for offering in offerings:
            off = {
                "id": offering["id"],
                "name": offering.get("name") or offering["id"],
            }
            if offering.get("description"):
                off["description"] = offering["description"]
            if offering.get("providers"):
                off["providers"] = list(offering["providers"])
                used_providers.update(offering["providers"])
            if offering.get("characteristics"):
                off["characteristics"] = offering["characteristics"]
            row["service_offerings"].append(off)
        services_out.append(row)

    provider_by_id = {row["id"]: row for row in providers if row.get("id")}
    providers_out: list[dict[str, Any]] = []
    for pid in sorted(used_providers):
        if pid in provider_by_id:
            providers_out.append(provider_by_id[pid])
        else:
            providers_out.append(
                {
                    "id": pid,
                    "name": pid,
                    "type": "cloud-infrastructure",
                    "substitutability": "medium",
                    "gdpr_dpa_signed": None,
                    "dora_notification_clause": None,
                    "certifications": [],
                    "risk_level": None,
                }
            )

    stacks_out: list[dict[str, Any]] = []
    for stack in stacks:
        item = {
            "id": stack["id"],
            "name": stack["name"],
            "description": stack.get("description") or stack["name"],
        }
        mappings = {key: value for key, value in (stack.get("mappings") or {}).items() if value not in (None, "", [], {})}
        if mappings:
            item["mappings"] = mappings
        stacks_out.append(item)

    _dump_yaml(catalog_dir / "catalog" / "technology-stacks.yaml", {"technology_stacks": stacks_out})
    _dump_yaml(catalog_dir / "catalog" / "services.yaml", {"services": services_out})
    _dump_yaml(catalog_dir / "catalog" / "ict-providers.yaml", {"ict_providers": providers_out})
    _dump_yaml(catalog_dir / "posture" / "service-posture.yaml", {"service_posture": []})


class OnboardingWizard:
    """Sequential onboarding pipeline with :view / :save / --resume."""

    def __init__(
        self,
        repo_root: Path,
        catalog_dir: Path,
        *,
        ask: Callable[[str], str] | None = None,
        echo: Callable[[str], None] | None = None,
    ) -> None:
        self.repo_root = Path(repo_root)
        self.catalog_dir = Path(catalog_dir)
        self._raw_ask = ask or input
        self.echo = echo or print
        self.state: dict[str, Any] = empty_state()
        self.frameworks: list[Framework] = discover_frameworks(self.repo_root)

    def ask(self, message: str, default: str | None = None) -> str:
        suffix = f" [{default}]" if default not in (None, "") else ""
        while True:
            raw = self._raw_ask(f"{message}{suffix}: ").strip()
            command = raw.lower()
            if command == ":view":
                self.echo(render_tree(self.state))
                continue
            if command == ":save":
                save_state(self.catalog_dir, self.state)
                raise SaveAndExit(str(self.catalog_dir / ".osm-scaffold-state.json"))
            if command == ":resume":
                self.echo(
                    "Already in a wizard session. After :save, continue with:\n"
                    "  python3 -m tools.osm_scaffold.cli --resume"
                )
                continue
            if command in {":help", "help"}:
                self.echo(
                    "Commands: :view  draft tree  ·  :save  checkpoint and exit  ·  "
                    ":resume  (CLI: python3 -m tools.osm_scaffold.cli --resume)"
                )
                continue
            if raw:
                return raw
            if default is not None:
                return default
            return ""

    def _checkpoint(self, step: str, cursor: int = 0) -> None:
        self.state["step"] = step
        self.state["cursor"] = cursor
        save_state(self.catalog_dir, self.state)

    def run(self, *, resume: bool = False) -> Path:
        self.echo(
            "OSM onboarding wizard — Principal Manager / Platform Lead / Head of Architecture.\n"
            "This establishes the canonical technological-service catalog.\n"
            "At any prompt: :view  (draft tree)  ·  :save  (checkpoint and exit)\n"
            "Resume after :save: python3 -m tools.osm_scaffold.cli --resume\n"
        )
        existing = load_state(self.catalog_dir)
        if resume:
            if existing is None:
                raise ScaffoldError(f"no checkpoint at {self.catalog_dir / '.osm-scaffold-state.json'}")
            self.state = existing
            self.echo(f"Resuming at step {self.state.get('step')}.")
        else:
            self.state = empty_state()
        step = self.state.get("step") or "frameworks"
        order = [
            ("frameworks", self.step_frameworks),
            ("domains", self.step_domains),
            ("draft", self.step_draft),
            ("refine_stacks", self.step_refine_stacks),
            ("refine_services", self.step_refine_services),
            ("refine_offerings", self.step_refine_offerings),
            ("params_stacks", self.step_params_stacks),
            ("params_services", self.step_params_services),
            ("params_offerings", self.step_params_offerings),
            ("compile", self.step_compile),
        ]
        started = False
        for name, handler in order:
            if name == step:
                started = True
            if started:
                handler()
        return self.catalog_dir

    def step_frameworks(self) -> None:
        self._checkpoint("frameworks")
        if self.state.get("frameworks") and self.state.get("step") != "frameworks":
            return
        self.echo("Step 1 — which external frameworks apply? Optional mappings only.")
        self.echo("Selecting a framework does not claim compliance.")
        for index, item in enumerate(self.frameworks, start=1):
            extra = f"  fields: {', '.join(item.stack_fields)}" if item.stack_fields else "  (no extra OSM fields)"
            self.echo(f"  {index}. {item.label}{extra}")
        raw = self.ask("Numbers comma-separated, or none", "none")
        if raw.lower() in {"none", "n", "skip"}:
            self.state["frameworks"] = []
        else:
            self.state["frameworks"] = [self.frameworks[i].id for i in _parse_indices(raw, len(self.frameworks))]
        self._checkpoint("domains")

    def step_domains(self) -> None:
        self._checkpoint("domains")
        self.echo("Step 2 — operational domains (capabilities, not vendors).")
        for index, domain in enumerate(DOMAINS, start=1):
            self.echo(f"  {index}. {domain.name}  — {domain.summary}")
        while True:
            raw = self.ask("Numbers comma-separated")
            try:
                refuse_vendor_label(raw)
            except ScaffoldError as exc:
                self.echo(str(exc))
                continue
            try:
                ids = [DOMAINS[i].id for i in _parse_indices(raw, len(DOMAINS))]
            except ScaffoldError as exc:
                self.echo(str(exc))
                continue
            if not ids:
                self.echo("Select at least one domain.")
                continue
            self.state["domains"] = ids
            break
        self._checkpoint("draft")

    def step_draft(self) -> None:
        self._checkpoint("draft")
        draft = propose_draft(self.repo_root, list(self.state.get("domains") or []))
        self.state["stacks"] = draft["stacks"]
        self.state["services"] = draft["services"]
        self.state["providers"] = draft["providers"]
        self.echo("Golden draft proposed from the reference catalogs:")
        self.echo(render_tree(self.state))
        if not self.state["stacks"]:
            self.echo("No golden stacks matched. Add stacks in the next step.")
        self.ask("Press enter to refine the hierarchy", "")
        self._checkpoint("refine_stacks")

    def step_refine_stacks(self) -> None:
        self._checkpoint("refine_stacks", int(self.state.get("cursor") or 0))
        self.echo("Step 3A — Technology Stacks. [k]eep  [r]ename  [d]elete")
        index = int(self.state.get("cursor") or 0)
        while index < len(self.state["stacks"]):
            self._checkpoint("refine_stacks", index)
            stack = self.state["stacks"][index]
            action = self.ask(
                f"Stack {stack['id']} ({stack.get('name')})  [k/r/d]",
                "k",
            ).lower()
            if action in {"d", "delete"}:
                stack_name = stack.get("name")
                del self.state["stacks"][index]
                self.state["services"] = [
                    service
                    for service in self.state["services"]
                    if service.get("technology_stack") != stack_name
                ]
                continue
            if action in {"r", "rename"}:
                new_name = self.ask("New stack name (capability, not a vendor)", stack["name"])
                refuse_vendor_label(new_name)
                old_name = stack["name"]
                stack["name"] = new_name
                for service in self.state["services"]:
                    if service.get("technology_stack") == old_name:
                        service["technology_stack"] = new_name
            index += 1
        while True:
            more = self.ask("Add a Technology Stack? [y/N]", "n").lower()
            if more not in {"y", "yes"}:
                break
            stack_id = slugify(self.ask("Stack id (slug)"))
            refuse_stack_id(stack_id)
            name = self.ask("Stack name", stack_id.replace("-", " ").title())
            refuse_vendor_label(name)
            description = self.ask("Stack description", f"{name} technological services.")
            self.state["stacks"].append(
                {"id": stack_id, "name": name, "description": description, "mappings": {}}
            )
        if not self.state["stacks"]:
            raise ScaffoldError("at least one Technology Stack is required")
        self.state["cursor"] = 0
        self._checkpoint("refine_services")

    def step_refine_services(self) -> None:
        self._checkpoint("refine_services", int(self.state.get("cursor") or 0))
        self.echo("Step 3B — Services. [k]eep  [m]ove  [d]elete")
        index = int(self.state.get("cursor") or 0)
        while index < len(self.state["services"]):
            self._checkpoint("refine_services", index)
            service = self.state["services"][index]
            action = self.ask(
                f"Service {service['id']} ({service.get('name')})  [k/m/d]",
                "k",
            ).lower()
            if action in {"d", "delete"}:
                del self.state["services"][index]
                continue
            if action in {"m", "move"}:
                target = self.ask("Move to stack id")
                match = next((row for row in self.state["stacks"] if row["id"] == target), None)
                if match is None:
                    self.echo(f"unknown stack {target!r}")
                else:
                    service["technology_stack"] = match["name"]
            index += 1
        while True:
            more = self.ask("Add a Service? [y/N]", "n").lower()
            if more not in {"y", "yes"}:
                break
            self._add_service()
        if not self.state["services"]:
            raise ScaffoldError("at least one Service is required")
        self.state["cursor"] = 0
        self._checkpoint("refine_offerings")

    def _add_service(self) -> None:
        stack_id = self.ask("Owning stack id", self.state["stacks"][0]["id"])
        stack = next((row for row in self.state["stacks"] if row["id"] == stack_id), None)
        if stack is None:
            raise ScaffoldError(f"unknown stack {stack_id!r}")
        slug = slugify(self.ask("Service slug (capability, not a product)"))
        name = self.ask("Service name", slug.replace("-", " ").title())
        refuse_service_slug(slug, name)
        description = self.ask("Service description", name)
        service_id = f"{stack['id']}.{slug}"
        self.state["services"].append(
            {
                "id": service_id,
                "name": name,
                "description": description,
                "technology_stack": stack["name"],
                "accountable": None,
                "version": "1.0.0",
                "valid_from": None,
                "valid_to": None,
                "lifecycle_state": "draft",
                "providers": [],
                "characteristics": [],
                "offerings": [],
            }
        )

    def step_refine_offerings(self) -> None:
        self._checkpoint("refine_offerings", int(self.state.get("cursor") or 0))
        self.echo("Step 3C — Offerings (requestable variants). [k]eep  [d]elete")
        service_index = int(self.state.get("cursor") or 0)
        while service_index < len(self.state["services"]):
            self._checkpoint("refine_offerings", service_index)
            service = self.state["services"][service_index]
            offerings = list(service.get("offerings") or [])
            off_i = 0
            while off_i < len(offerings):
                offering = offerings[off_i]
                action = self.ask(
                    f"Offering {offering['id']} ({offering.get('name')})  [k/d]",
                    "k",
                ).lower()
                if action in {"d", "delete"}:
                    del offerings[off_i]
                    continue
                off_i += 1
            while True:
                more = self.ask(f"Add an Offering to {service['id']}? [y/N]", "n").lower()
                if more not in {"y", "yes"}:
                    break
                offerings.append(self._new_offering(service))
            if not offerings:
                self.echo(f"{service['id']} needs at least one Offering.")
                offerings.append(self._new_offering(service))
            service["offerings"] = offerings
            service_index += 1
        self.state["cursor"] = 0
        self._checkpoint("params_stacks")

    def _new_offering(self, service: dict[str, Any]) -> dict[str, Any]:
        slug = slugify(self.ask("Offering slug"))
        name = self.ask("Offering name", slug.replace("-", " "))
        refuse_offering_slug(slug, name)
        offering_id = f"{service['id']}.{slug}"
        return {
            "id": offering_id,
            "name": name,
            "providers": [],
            "characteristics": [],
        }

    def step_params_stacks(self) -> None:
        self._checkpoint("params_stacks")
        self.echo("Step 4 — must-have fields. Skip optional mappings with enter.")
        selected = set(self.state.get("frameworks") or [])
        active = [item for item in self.frameworks if item.id in selected and item.stack_fields]
        for stack in self.state["stacks"]:
            stack["description"] = self.ask(
                f"{stack['id']} description",
                stack.get("description") or stack["name"],
            )
            mappings = dict(stack.get("mappings") or {})
            for framework in active:
                self._fill_stack_mappings(stack, mappings, framework)
            stack["mappings"] = mappings
        self._checkpoint("params_services")

    def _fill_stack_mappings(self, stack: dict[str, Any], mappings: dict[str, Any], framework: Framework) -> None:
        for field in framework.stack_fields:
            if field == "togaf_domain":
                value = self.ask(
                    f"{stack['id']} TOGAF domain {TOGAF_DOMAINS} (empty to skip)",
                    "",
                )
                if value:
                    mappings["togaf_domain"] = value
            elif field == "tbm_tower":
                value = self.ask(f"{stack['id']} TBM tower (empty to skip)", "")
                if value:
                    mappings["tbm_tower"] = value
            elif field == "tbm_sub_tower":
                value = self.ask(f"{stack['id']} TBM sub-tower (empty to skip)", "")
                if value:
                    mappings["tbm_sub_tower"] = value
            elif field == "iso27001":
                value = self.ask(f"{stack['id']} ISO 27001 locators (empty to skip)", "")
                if value:
                    mappings["iso27001"] = value
            elif field == "iso27701":
                value = self.ask(f"{stack['id']} ISO 27701 locators (empty to skip)", "")
                if value:
                    mappings["iso27701"] = value
            elif field == "nist_csf":
                value = self.ask(
                    f"{stack['id']} NIST CSF functions {NIST_FUNCTIONS} comma-separated (empty to skip)",
                    "",
                )
                if value:
                    mappings["nist_csf"] = [part.strip() for part in value.split(",") if part.strip()]
            elif field == "gdpr":
                value = self.ask(f"{stack['id']} GDPR locators (empty to skip)", "")
                if value:
                    mappings["gdpr"] = value
            elif field == "dora":
                pillar = self.ask(f"{stack['id']} DORA pillar (empty to skip)", "")
                criticality = self.ask(f"{stack['id']} DORA criticality {DORA_CRITICALITY} (empty to skip)", "")
                if pillar or criticality:
                    mappings["dora"] = {
                        "pillar": pillar or "ICT Risk Management",
                        "criticality": criticality or "standard",
                    }
            elif field == "ai_act":
                contains = self.ask(f"{stack['id']} contains AI systems? [y/N]", "n").lower()
                risk = self.ask(f"{stack['id']} AI Act max_risk_class {AI_RISK} (empty to skip)", "")
                mappings["ai_act"] = {
                    "contains_ai_systems": contains in {"y", "yes", "true"},
                    "max_risk_class": risk or "not-applicable",
                }

    def step_params_services(self) -> None:
        self._checkpoint("params_services")
        for service in self.state["services"]:
            service["accountable"] = self.ask(
                f"{service['id']} Service Owner (accountable)",
                service.get("accountable") or "Service Owner",
            )
            lifecycle = self.ask(
                f"{service['id']} lifecycle_state {LIFECYCLE}",
                service.get("lifecycle_state") or "draft",
            )
            if lifecycle not in LIFECYCLE:
                raise ScaffoldError(f"lifecycle_state {lifecycle!r} is not an OSM value")
            service["lifecycle_state"] = lifecycle
            service["version"] = self.ask(f"{service['id']} version", service.get("version") or "1.0.0")
            if not service.get("valid_from"):
                service["valid_from"] = date.today().isoformat()
        self._checkpoint("params_offerings")

    def step_params_offerings(self) -> None:
        self._checkpoint("params_offerings")
        known = {row["id"]: row for row in self.state.get("providers") or []}
        for service in self.state["services"]:
            for offering in service.get("offerings") or []:
                raw = self.ask(
                    f"{offering['id']} providers[] (comma-separated legal-seller ids, empty if self-operated)",
                    ",".join(offering.get("providers") or []),
                )
                providers = [slugify(part) for part in raw.split(",") if part.strip()]
                offering["providers"] = providers
                for pid in providers:
                    if pid in known:
                        continue
                    name = self.ask(f"New ICT Provider {pid} name", pid)
                    ptype = self.ask(f"{pid} type {PROVIDER_TYPES}", "cloud-infrastructure")
                    if ptype not in PROVIDER_TYPES:
                        raise ScaffoldError(f"provider type {ptype!r} is not an OSM ICT Provider type")
                    subst = self.ask(f"{pid} substitutability {SUBSTITUTABILITY}", "medium")
                    known[pid] = {
                        "id": pid,
                        "name": name,
                        "type": ptype,
                        "substitutability": subst,
                        "gdpr_dpa_signed": None,
                        "dora_notification_clause": None,
                        "certifications": [],
                        "risk_level": None,
                    }
                chars = list(offering.get("characteristics") or [])
                more = self.ask(
                    f"{offering['id']} add a distinguishing characteristic? [y/N]",
                    "n",
                ).lower()
                if more in {"y", "yes"}:
                    cname = slugify(self.ask("characteristic name")).replace("-", "_")
                    ctype = self.ask("value_type [string/number/boolean/date]", "string")
                    cvalue = self.ask("value (empty if unset)", "")
                    item: dict[str, Any] = {"name": cname, "value_type": ctype}
                    if cvalue:
                        item["value"] = cvalue
                    chars.append(item)
                offering["characteristics"] = chars
        self.state["providers"] = list(known.values())
        self._checkpoint("compile")

    def step_compile(self) -> None:
        self._checkpoint("compile")
        write_catalog_from_state(self.catalog_dir, self.state)
        clear_state(self.catalog_dir)
        self.echo(f"Catalog written under {self.catalog_dir.resolve()}")
        self.echo("  catalog/technology-stacks.yaml")
        self.echo("  catalog/services.yaml")
        self.echo("  catalog/ict-providers.yaml")
        self.echo("  posture/service-posture.yaml  (empty — unknown is better than invented)")
        self.echo(
            f"Next: python3 -m tools.osm_lint.cli --catalog {self.catalog_dir}"
        )


def _parse_indices(raw: str, count: int) -> list[int]:
    if not raw.strip():
        return []
    indices: list[int] = []
    for part in raw.split(","):
        part = part.strip()
        if not part:
            continue
        if not part.isdigit():
            raise ScaffoldError(f"not a number: {part!r}")
        number = int(part)
        if number < 1 or number > count:
            raise ScaffoldError(f"choice {number} is out of range 1–{count}")
        index = number - 1
        if index not in indices:
            indices.append(index)
    return indices
